import { ApiCallError } from "../../core/api/ApiCallError.js";
export const failedLmntCallResponseHandler = async ({ response, url, requestBodyValues }) => {
    const responseBody = await response.text();
    try {
        // TODO implement LmntError
        return new ApiCallError({
            message: responseBody,
            statusCode: response.status,
            url,
            requestBodyValues,
        });
    }
    catch (error) {
        if (error instanceof Error) {
            if (error.name === "AbortError" || error instanceof ApiCallError) {
                throw error;
            }
        }
        throw new ApiCallError({
            message: responseBody,
            cause: error,
            statusCode: response.status,
            url,
            requestBodyValues,
        });
    }
};
